name: "Secrets"

on:
  push:
    branches:
      - main

jobs:
  secrets:
    name: "Secrets"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.head_ref }}

    ############## Version 1 ##############
    #- name: "Trufflehog Scan"
    #  uses: trufflesecurity/trufflehog@main
    #  with:
    #    extra_args: --only-verified
    #######################################
    ############## Version 2 ##############
    #    base: ""
    #    head: ${{ github.ref_name }}
    #######################################